// ! Auto-generated by scripts/generate-types.mjs — DO NOT EDIT
// ? Derived from package.json exports. Regenerate with: node scripts/generate-types.mjs

import * as ChronosDate from 'chronos-date';
import * as Constants from 'chronos-date/constants';
import * as Guards from 'chronos-date/guards';
import * as PluginsBanglaPlugin from 'chronos-date/plugins/banglaPlugin';
import * as PluginsBusinessPlugin from 'chronos-date/plugins/businessPlugin';
import * as PluginsDateRangePlugin from 'chronos-date/plugins/dateRangePlugin';
import * as PluginsDayPartPlugin from 'chronos-date/plugins/dayPartPlugin';
import * as PluginsDurationPlugin from 'chronos-date/plugins/durationPlugin';
import * as PluginsFromNowPlugin from 'chronos-date/plugins/fromNowPlugin';
import * as PluginsGreetingPlugin from 'chronos-date/plugins/greetingPlugin';
import * as PluginsPalindromePlugin from 'chronos-date/plugins/palindromePlugin';
import * as PluginsRelativeTimePlugin from 'chronos-date/plugins/relativeTimePlugin';
import * as PluginsRoundPlugin from 'chronos-date/plugins/roundPlugin';
import * as PluginsSeasonPlugin from 'chronos-date/plugins/seasonPlugin';
import * as PluginsTimeZonePlugin from 'chronos-date/plugins/timeZonePlugin';
import * as PluginsZodiacPlugin from 'chronos-date/plugins/zodiacPlugin';
import * as Types from 'chronos-date/types';
import * as Utils from 'chronos-date/utils';

type ChronosModule = 'chronos-date' | `chronos-date/${string}`;

export const MODULES: Record<ChronosModule, unknown> = {
	'chronos-date': ChronosDate,
	'chronos-date/constants': Constants,
	'chronos-date/guards': Guards,
	'chronos-date/plugins/banglaPlugin': PluginsBanglaPlugin,
	'chronos-date/plugins/businessPlugin': PluginsBusinessPlugin,
	'chronos-date/plugins/dateRangePlugin': PluginsDateRangePlugin,
	'chronos-date/plugins/dayPartPlugin': PluginsDayPartPlugin,
	'chronos-date/plugins/durationPlugin': PluginsDurationPlugin,
	'chronos-date/plugins/fromNowPlugin': PluginsFromNowPlugin,
	'chronos-date/plugins/greetingPlugin': PluginsGreetingPlugin,
	'chronos-date/plugins/palindromePlugin': PluginsPalindromePlugin,
	'chronos-date/plugins/relativeTimePlugin': PluginsRelativeTimePlugin,
	'chronos-date/plugins/roundPlugin': PluginsRoundPlugin,
	'chronos-date/plugins/seasonPlugin': PluginsSeasonPlugin,
	'chronos-date/plugins/timeZonePlugin': PluginsTimeZonePlugin,
	'chronos-date/plugins/zodiacPlugin': PluginsZodiacPlugin,
	'chronos-date/types': Types,
	'chronos-date/utils': Utils,
};

export { ChronosDate, type ChronosModule };
